from datetime import UTC, datetime, timedelta

from fastapi.testclient import TestClient
from sqlalchemy import select
from sqlalchemy.orm import Session

from app.models import AuditLog, SecuritySignal
from app.services.self_monitoring import SelfMonitoringService
from tests.conftest import OTHER_ORG_ID, TEST_ORG_ID


def _audit(
    session: Session,
    action: str,
    actor: str = "user-1",
    details: dict | None = None,
    organization_id=TEST_ORG_ID,
):
    session.add(
        AuditLog(
            organization_id=organization_id,
            actor_type="user",
            actor_id=actor,
            action=action,
            resource_type="test",
            resource_id=None,
            details=details or {},
        )
    )


def test_self_monitoring_emits_deterministic_signals_and_is_idempotent(session: Session) -> None:
    for _ in range(3):
        _audit(session, "identity.capability_changed")
    for _ in range(10):
        _audit(session, "http.request", details={"status_code": 404, "client_ip": "10.0.0.1"})
    _audit(session, "detection_rule.configured", details={"enabled": False})
    session.commit()
    now = datetime.now(UTC)

    service = SelfMonitoringService(session, TEST_ORG_ID)
    first = service.evaluate(now=now)
    session.commit()
    second = service.evaluate(now=now + timedelta(seconds=1))
    session.commit()

    types = {item.signal_type for item in first}
    assert {"capability_churn", "mass_enumeration", "security_control_disabled"} <= types
    assert len(second) == len(first)
    signals = list(session.scalars(select(SecuritySignal)))
    assert len(signals) == len(first)
    assert all(item.occurrences == 2 for item in signals)
    generated = session.scalar(
        select(AuditLog).where(AuditLog.action == "security.signal_generated")
    )
    assert generated is not None
    updated = list(
        session.scalars(select(AuditLog).where(AuditLog.action == "security.signal_updated"))
    )
    # Ledger/audit events generated by the detector are excluded from its
    # inputs: one deduplicated update per signal, never a feedback loop.
    assert len(updated) == len(first)


def test_self_monitoring_ignores_old_events_and_foreign_tenant(session: Session) -> None:
    old = datetime.now(UTC) - timedelta(hours=1)
    _audit(session, "identity.capability_changed")
    session.flush()
    old_log = session.scalar(select(AuditLog).order_by(AuditLog.created_at.desc()))
    assert old_log is not None
    old_log.created_at = old
    _audit(session, "security.cross_tenant_attempt", organization_id=OTHER_ORG_ID)
    session.commit()
    assert SelfMonitoringService(session, TEST_ORG_ID).evaluate() == []


def test_security_signals_are_admin_only_and_tenant_scoped(
    client: TestClient, session: Session
) -> None:
    _audit(session, "security.cross_tenant_attempt", details={"cross_tenant": True})
    session.commit()
    SelfMonitoringService(session, TEST_ORG_ID).evaluate()
    session.commit()
    response = client.get("/api/v1/security/signals")
    assert response.status_code == 200
    assert response.json()[0]["signal_type"] == "cross_tenant_attempt"
