"""async wazuh integrations

Revision ID: 5bdba41590e5
Revises: 5ea439a9d64a
Create Date: 2026-08-31 11:33:46.943663
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '5bdba41590e5'
down_revision: Union[str, None] = '5ea439a9d64a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('integration_accounts',
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('integration_type', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('base_url', sa.String(length=2048), nullable=False),
    sa.Column('credential_reference', sa.String(length=255), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('last_success_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'name')
    )
    op.create_index(op.f('ix_integration_accounts_organization_id'), 'integration_accounts', ['organization_id'], unique=False)
    op.create_index('ix_integrations_org_type', 'integration_accounts', ['organization_id', 'integration_type'], unique=False)
    op.create_table('dead_letter_events',
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('integration_account_id', sa.Uuid(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('error', sa.Text(), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('first_failed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_failed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['integration_account_id'], ['integration_accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dead_letter_events_integration_account_id'), 'dead_letter_events', ['integration_account_id'], unique=False)
    op.create_index(op.f('ix_dead_letter_events_organization_id'), 'dead_letter_events', ['organization_id'], unique=False)
    op.create_index('ix_dlq_org_status', 'dead_letter_events', ['organization_id', 'status'], unique=False)
    op.create_table('integration_checkpoints',
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('integration_account_id', sa.Uuid(), nullable=False),
    sa.Column('stream', sa.String(length=100), nullable=False),
    sa.Column('last_position', sa.String(length=500), nullable=True),
    sa.Column('last_timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cursor', sa.JSON(), nullable=True),
    sa.Column('last_success_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['integration_account_id'], ['integration_accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'integration_account_id', 'stream')
    )
    op.create_index(op.f('ix_integration_checkpoints_integration_account_id'), 'integration_checkpoints', ['integration_account_id'], unique=False)
    op.create_index(op.f('ix_integration_checkpoints_organization_id'), 'integration_checkpoints', ['organization_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_integration_checkpoints_organization_id'), table_name='integration_checkpoints')
    op.drop_index(op.f('ix_integration_checkpoints_integration_account_id'), table_name='integration_checkpoints')
    op.drop_table('integration_checkpoints')
    op.drop_index('ix_dlq_org_status', table_name='dead_letter_events')
    op.drop_index(op.f('ix_dead_letter_events_organization_id'), table_name='dead_letter_events')
    op.drop_index(op.f('ix_dead_letter_events_integration_account_id'), table_name='dead_letter_events')
    op.drop_table('dead_letter_events')
    op.drop_index('ix_integrations_org_type', table_name='integration_accounts')
    op.drop_index(op.f('ix_integration_accounts_organization_id'), table_name='integration_accounts')
    op.drop_table('integration_accounts')
    # ### end Alembic commands ###
