"""initial schema

Revision ID: 5ea439a9d64a
Revises:
Create Date: 2026-08-31 11:12:07.387811
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "5ea439a9d64a"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "organizations",
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("slug", sa.String(length=100), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_organizations_slug"), "organizations", ["slug"], unique=True)
    op.create_table(
        "audit_logs",
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("actor_type", sa.String(length=50), nullable=False),
        sa.Column("actor_id", sa.String(length=255), nullable=True),
        sa.Column("action", sa.String(length=255), nullable=False),
        sa.Column("resource_type", sa.String(length=100), nullable=False),
        sa.Column("resource_id", sa.String(length=255), nullable=True),
        sa.Column("details", sa.JSON(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_audit_logs_organization_id"), "audit_logs", ["organization_id"], unique=False
    )
    op.create_index(
        "ix_audit_org_created", "audit_logs", ["organization_id", "created_at"], unique=False
    )
    op.create_table(
        "endpoints",
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("hostname", sa.String(length=255), nullable=False),
        sa.Column("operating_system", sa.String(length=255), nullable=True),
        sa.Column("ip_address", sa.String(length=45), nullable=True),
        sa.Column("agent_id", sa.String(length=255), nullable=False),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("last_seen", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("organization_id", "agent_id"),
    )
    op.create_index(
        "ix_endpoints_org_status", "endpoints", ["organization_id", "status"], unique=False
    )
    op.create_index(
        op.f("ix_endpoints_organization_id"), "endpoints", ["organization_id"], unique=False
    )
    op.create_table(
        "incidents",
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("title", sa.String(length=500), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("severity", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_incidents_org_status", "incidents", ["organization_id", "status"], unique=False
    )
    op.create_index(
        op.f("ix_incidents_organization_id"), "incidents", ["organization_id"], unique=False
    )
    op.create_table(
        "users",
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("display_name", sa.String(length=255), nullable=False),
        sa.Column("role", sa.String(length=50), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("organization_id", "email"),
    )
    op.create_index(op.f("ix_users_organization_id"), "users", ["organization_id"], unique=False)
    op.create_table(
        "alerts",
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("endpoint_id", sa.Uuid(), nullable=False),
        sa.Column("source", sa.String(length=50), nullable=False),
        sa.Column("external_id", sa.String(length=255), nullable=False),
        sa.Column("title", sa.String(length=500), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("severity", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("severity >= 0 AND severity <= 10", name="ck_alert_severity"),
        sa.ForeignKeyConstraint(["endpoint_id"], ["endpoints.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("organization_id", "source", "external_id"),
    )
    op.create_index(op.f("ix_alerts_endpoint_id"), "alerts", ["endpoint_id"], unique=False)
    op.create_index("ix_alerts_org_status", "alerts", ["organization_id", "status"], unique=False)
    op.create_index(op.f("ix_alerts_organization_id"), "alerts", ["organization_id"], unique=False)
    op.create_table(
        "security_events",
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("endpoint_id", sa.Uuid(), nullable=False),
        sa.Column("source", sa.String(length=50), nullable=False),
        sa.Column("external_id", sa.String(length=255), nullable=False),
        sa.Column("event_type", sa.String(length=100), nullable=False),
        sa.Column("severity", sa.Integer(), nullable=False),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("raw_payload", sa.JSON(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["endpoint_id"], ["endpoints.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("organization_id", "source", "external_id"),
    )
    op.create_index(
        "ix_events_org_occurred",
        "security_events",
        ["organization_id", "occurred_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_security_events_endpoint_id"), "security_events", ["endpoint_id"], unique=False
    )
    op.create_index(
        op.f("ix_security_events_organization_id"),
        "security_events",
        ["organization_id"],
        unique=False,
    )
    op.create_table(
        "alert_security_events",
        sa.Column("alert_id", sa.Uuid(), nullable=False),
        sa.Column("security_event_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(["alert_id"], ["alerts.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["security_event_id"], ["security_events.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("alert_id", "security_event_id"),
    )
    op.create_table(
        "incident_alerts",
        sa.Column("incident_id", sa.Uuid(), nullable=False),
        sa.Column("alert_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(["alert_id"], ["alerts.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["incident_id"], ["incidents.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("incident_id", "alert_id"),
    )
    op.create_table(
        "investigations",
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("alert_id", sa.Uuid(), nullable=True),
        sa.Column("incident_id", sa.Uuid(), nullable=True),
        sa.Column("risk_score", sa.Integer(), nullable=False),
        sa.Column("classification", sa.String(length=100), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("evidence", sa.JSON(), nullable=False),
        sa.Column("explanation", sa.Text(), nullable=False),
        sa.Column("recommended_actions", sa.JSON(), nullable=False),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "(alert_id IS NOT NULL AND incident_id IS NULL) OR (alert_id IS NULL AND incident_id IS NOT NULL)",
            name="ck_investigation_single_subject",
        ),
        sa.CheckConstraint("confidence >= 0 AND confidence <= 1", name="ck_confidence"),
        sa.CheckConstraint("risk_score >= 0 AND risk_score <= 100", name="ck_risk_score"),
        sa.ForeignKeyConstraint(["alert_id"], ["alerts.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["incident_id"], ["incidents.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_investigations_alert_id"), "investigations", ["alert_id"], unique=False
    )
    op.create_index(
        op.f("ix_investigations_incident_id"), "investigations", ["incident_id"], unique=False
    )
    op.create_index(
        "ix_investigations_org_status",
        "investigations",
        ["organization_id", "status"],
        unique=False,
    )
    op.create_index(
        op.f("ix_investigations_organization_id"),
        "investigations",
        ["organization_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_investigations_organization_id"), table_name="investigations")
    op.drop_index("ix_investigations_org_status", table_name="investigations")
    op.drop_index(op.f("ix_investigations_incident_id"), table_name="investigations")
    op.drop_index(op.f("ix_investigations_alert_id"), table_name="investigations")
    op.drop_table("investigations")
    op.drop_table("incident_alerts")
    op.drop_table("alert_security_events")
    op.drop_index(op.f("ix_security_events_organization_id"), table_name="security_events")
    op.drop_index(op.f("ix_security_events_endpoint_id"), table_name="security_events")
    op.drop_index("ix_events_org_occurred", table_name="security_events")
    op.drop_table("security_events")
    op.drop_index(op.f("ix_alerts_organization_id"), table_name="alerts")
    op.drop_index("ix_alerts_org_status", table_name="alerts")
    op.drop_index(op.f("ix_alerts_endpoint_id"), table_name="alerts")
    op.drop_table("alerts")
    op.drop_index(op.f("ix_users_organization_id"), table_name="users")
    op.drop_table("users")
    op.drop_index(op.f("ix_incidents_organization_id"), table_name="incidents")
    op.drop_index("ix_incidents_org_status", table_name="incidents")
    op.drop_table("incidents")
    op.drop_index(op.f("ix_endpoints_organization_id"), table_name="endpoints")
    op.drop_index("ix_endpoints_org_status", table_name="endpoints")
    op.drop_table("endpoints")
    op.drop_index("ix_audit_org_created", table_name="audit_logs")
    op.drop_index(op.f("ix_audit_logs_organization_id"), table_name="audit_logs")
    op.drop_table("audit_logs")
    op.drop_index(op.f("ix_organizations_slug"), table_name="organizations")
    op.drop_table("organizations")
    # ### end Alembic commands ###
